export const env = {
  DATABASE_URL: process.env.DATABASE_URL!,
  REDIS_URL: process.env.REDIS_URL!,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL!,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET!,
  TIDAL_CLIENT_ID: process.env.TIDAL_CLIENT_ID!,
  TIDAL_CLIENT_SECRET: process.env.TIDAL_CLIENT_SECRET!,
  TIDAL_REDIRECT_URI: process.env.TIDAL_REDIRECT_URI!,
  TIDAL_AUTH_URL: process.env.TIDAL_AUTH_URL!,
  TIDAL_TOKEN_URL: process.env.TIDAL_TOKEN_URL!,
  TIDAL_API_BASE: process.env.TIDAL_API_BASE!,
  LASTFM_API_KEY: process.env.LASTFM_API_KEY!,
  LASTFM_API_SECRET: process.env.LASTFM_API_SECRET!,
  LASTFM_REDIRECT_URI: process.env.LASTFM_REDIRECT_URI!
}
